#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea)
skip_tags: true


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2019 Preview

# scripts that are called at very beginning, before repo cloning
init:
# If you’re on a Windows machine, this converts LF endings into CRLF when you check out code.
# https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_code_core_autocrlf_code
- git config --global core.autocrlf true

# environment variables
environment:
  CODECOV_TOKEN: 4ac7aa20-510a-4cbe-b9ff-452ac4ac2ff9

# build cache to preserve files/folders between builds
cache:
  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - packages -> **\packages.config


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  # path to Visual Studio solution or project
  project: AllProjects.sln
  # MSBuild verbosity level
  verbosity: minimal

# scripts to run before build
before_build:
- nuget restore


#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  - cd build
  #- pwsh: .\opencover.ps1


#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  # Email
- provider: Email
  to:
  - jeanbern@ualberta.ca
  # optional
  subject: AppVeyor Notification
  # optional
  message: 'If this is annoying, settings are here: https://ci.appveyor.com/project/jeanbern/portent/settings/notifications'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
